import 'package:flutter_test/flutter_test.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart';

import 'package:nihaisha_app/data/database_helper.dart';
import 'package:nihaisha_app/services/license_service.dart';

void main() {
  const device = '00112233445566778899aabbccddeeff';
  // Oracle generated by the supplied 汉唐中医卡密器 algorithm for 2099-12-31.
  const generatorOracle = 'C04hC4GbBStJqRPBmYu';

  setUpAll(() {
    sqfliteFfiInit();
    databaseFactory = databaseFactoryFfi;
  });

  setUp(() async {
    DatabaseHelper.resetForTest();
    await DatabaseHelper.instance.setSetting('device_id', device);
  });

  test('supplied generator oracle verifies field-for-field', () async {
    final info = await LicenseService.verifyAt(
      generatorOracle,
      DateTime(2099, 12, 30, 23, 59),
    );
    expect(info.result, LicenseResult.valid);
    expect(info.deviceId, device);
    expect(info.code, generatorOracle);
    expect(info.expiryLabel, '2099-12-31');
  });

  test('到期日全天有效，次日起立即过期', () async {
    final lastDay = await LicenseService.verifyAt(
      generatorOracle,
      DateTime(2099, 12, 31, 23, 59, 59),
    );
    expect(lastDay.result, LicenseResult.valid);
    expect(
      lastDay.remainingLabelAt(DateTime(2099, 12, 31, 23, 59, 59)),
      '今日到期（剩余不到1天）',
    );

    final nextDay = await LicenseService.verifyAt(
      generatorOracle,
      DateTime(2100, 1, 1),
    );
    expect(nextDay.result, LicenseResult.expired);
  });

  test('card is bound to its device id', () async {
    await DatabaseHelper.instance.setSetting(
      'device_id',
      'ffeeddccbbaa99887766554433221100',
    );
    expect(
      (await LicenseService.verify(generatorOracle)).result,
      LicenseResult.invalid,
    );
  });

  test('bad format is rejected', () async {
    expect(
      (await LicenseService.verify('bad')).result,
      LicenseResult.badFormat,
    );
  });

  test('activation persists and cold-start restores', () async {
    expect((await LicenseService.activate(generatorOracle)).isValid, isTrue);
    final restored = await LicenseService.current();
    expect(restored.isValid, isTrue);
    expect(restored.deviceId, device);
    expect(restored.expiryLabel, '2099-12-31');
  });
}
